# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('account_name', models.CharField(default='', max_length=100)),
                ('isn_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('credit_card_number', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='BuyCourse',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('bank_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buycourse_bankdetails', to='technical.BankDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default='')),
                ('details', models.TextField(default='0')),
                ('batch', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grades', models.CharField(max_length=10)),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='technical.Education')),
            ],
        ),
        migrations.AddField(
            model_name='buycourse',
            name='course_name',
            field=models.ManyToManyField(related_name='buycourse_coursename', to='technical.Course'),
        ),
        migrations.AddField(
            model_name='buycourse',
            name='student_name',
            field=models.ManyToManyField(related_name='buycourse_studentname', to='technical.Student'),
        ),
    ]
