# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0002_auto_20180621_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='bank_deials_id',
            new_name='bank_detials_id',
        ),
    ]
