# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0004_remove_buycourse_bank_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buycourse',
            old_name='student_name',
            new_name='student_id',
        ),
    ]
