# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0005_auto_20180622_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trascat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transact_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical.Student')),
            ],
        ),
    ]
