# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0008_trascat_transact_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=100)),
                ('input_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
