# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0009_stockpredict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpredict',
            name='input_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
