# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0010_auto_20180626_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPredictSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=100)),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
